# Site settings
title: Dock-a-thon - Docker Hack-a-thon
# email: your-email@domain.com
description: ""
baseurl: ""
url: "https://dock-a-thon.github.io/"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink"]
permalink: pretty
